# Generated by Django 4.2.18 on 2026-07-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('subgroup_number', models.PositiveSmallIntegerField(blank=True, help_text='Может отсутствовать', null=True, verbose_name='Номер подгруппы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
