# Generated by Django 4.2.18 on 2026-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.CharField(default='', help_text='Используется для входа в систему', max_length=100, unique=True, verbose_name='Логин'),
        ),
    ]
