# Generated by Django 4.2.18 on 2026-07-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subgroup_number',
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('subgroup_number', models.PositiveSmallIntegerField(blank=True, help_text='Может отсутствовать', null=True, verbose_name='Номер подгруппы')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'unique_together': {('group_number', 'subgroup_number')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.studentgroup', verbose_name='Группа'),
        ),
    ]
