# Generated by Django 4.2.18 on 2026-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_group_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='code',
            field=models.CharField(blank=True, help_text='Пример: 6-05-0612-01, 1-40-01-01', max_length=20, null=True, unique=True, verbose_name='Шифр группы'),
        ),
    ]
