# Generated by Django 4.2.18 on 2026-07-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umo', '0001_initial'),
        ('students', '0008_studentgroup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='code',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='shifr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='umo.shifr', verbose_name='Шифр'),
        ),
    ]
