# Generated by Django 4.2.18 on 2026-07-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_create_roles'),
        ('students', '0009_remove_studentgroup_code_studentgroup_shifr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='enrollment_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Начало обучения', null=True, verbose_name='Год поступления'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups', to='structure.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='study_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок обучения (месяцев)'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='study_duration_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок обучения (лет)'),
        ),
    ]
