# Generated by Django 4.2.18 on 2026-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentgroup_enrollment_year_studentgroup_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='education_form',
            field=models.CharField(blank=True, choices=[('daytime', 'Дневная'), ('correspondence', 'Заочная')], max_length=20, null=True, verbose_name='Форма получения образования'),
        ),
    ]
