# Generated by Django 4.2.18 on 2026-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentgroup_education_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='record_book_number',
            field=models.CharField(blank=True, default='', help_text='Необязательное поле', max_length=50, verbose_name='Номер зачётной книжки'),
        ),
    ]
