# Generated by Django 4.2.18 on 2026-07-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_add_record_book_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(verbose_name='ID оригинального студента')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('record_book_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер зачётной книжки')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль (хэш)')),
                ('group_name', models.CharField(max_length=100, verbose_name='Группа')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Удалённый студент',
                'verbose_name_plural': 'Удалённые студенты',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
