# Generated by Django 4.2.18 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_deletedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedstudent',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID группы'),
        ),
    ]
