# Generated by Django 4.2.18 on 2026-07-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_add_group_id_to_deletedstudent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='subgroup_number',
        ),
    ]
