# Generated by Django 4.2.18 on 2026-07-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umo', '0003_shifr_faculty'),
        ('students', '0015_remove_subgroup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='shifr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='umo.shifr', verbose_name='Код специальности'),
        ),
    ]
