# Generated by Django 4.2.18 on 2026-07-15 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('identifier', models.CharField(help_text='Для внутренних нужд, не отображается в интерфейсе', max_length=50, unique=True, verbose_name='Идентификатор')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='subject.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('edit', 'Редактирование'), ('create_delete', 'Создание и удаление'), ('view', 'Только просмотр')], max_length=20, verbose_name='Уровень доступа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='course.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Права пользователя на курс',
                'verbose_name_plural': 'Права пользователей на курсы',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CourseGroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Группа студентов курса',
                'verbose_name_plural': 'Группы студентов курсов',
                'unique_together': {('course', 'group_number')},
            },
        ),
    ]
