# Generated by Django 4.2.18 on 2026-07-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0002_alter_course_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('edit', 'Редактирование'), ('create_delete', 'Создание и удаление'), ('view', 'Только просмотр')], max_length=20, verbose_name='Уровень доступа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='course.course', verbose_name='Курс')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_permissions', to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Права группы на курс',
                'verbose_name_plural': 'Права групп на курсы',
                'unique_together': {('course', 'group')},
            },
        ),
    ]
