# Generated by Django 4.2.18 on 2026-07-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_group_number_and_more'),
        ('course', '0003_coursegrouppermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursegroupstudent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coursegroupstudent',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.studentgroup', verbose_name='Группа'),
        ),
        migrations.AlterUniqueTogether(
            name='coursegroupstudent',
            unique_together={('course', 'group')},
        ),
        migrations.RemoveField(
            model_name='coursegroupstudent',
            name='group_number',
        ),
    ]
