# Generated by Django 4.2.18 on 2026-07-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursegroupstudent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrouppermission',
            name='permission',
            field=models.CharField(choices=[('edit', 'Редактирование'), ('create_delete', 'Создание и удаление'), ('view', 'Только просмотр'), ('full_access', 'Полный доступ')], max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='courseuserpermission',
            name='permission',
            field=models.CharField(choices=[('edit', 'Редактирование'), ('create_delete', 'Создание и удаление'), ('view', 'Только просмотр'), ('full_access', 'Полный доступ')], max_length=20, verbose_name='Уровень доступа'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название раздела')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Раздел курса',
                'verbose_name_plural': 'Разделы курсов',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'name')},
            },
        ),
    ]
