# Generated by Django 4.2.18 on 2026-07-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_coursegrouppermission_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_title', models.CharField(help_text='Как пользователь называет эту единицу: «Тема», «Параграф», «Лекция» и т.п.', max_length=100, verbose_name='Название сущности')),
                ('content', models.CharField(help_text='Собственно название темы, например «Введение в программирование»', max_length=500, verbose_name='Содержание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.coursesection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема раздела',
                'verbose_name_plural': 'Темы разделов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
