# Generated by Django 4.2.18 on 2026-07-15 13:53

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursetopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название единицы')),
                ('content_type', models.CharField(choices=[('file', 'Файл')], default='file', max_length=30, verbose_name='Тип содержимого')),
                ('file', models.FileField(blank=True, help_text='Загружаемый файл: PDF, DOC, DOCX, JPG и т.д.', null=True, upload_to=course.models.learning_unit_upload_to, verbose_name='Файл')),
                ('link', models.CharField(blank=True, help_text='Ссылка на внешний ресурс или внутренний модуль', max_length=500, null=True, verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='course.coursetopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Единица обучения',
                'verbose_name_plural': 'Единицы обучения',
                'ordering': ['order', 'id'],
            },
        ),
    ]
