# Generated by Django 4.2.18 on 2026-07-16 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_learningunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Если единица привязана напрямую к разделу без темы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_units', to='course.coursesection', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='course.coursetopic', verbose_name='Тема'),
        ),
    ]
