# Generated by Django 4.2.18 on 2026-07-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_learningunit_add_section_topic_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='visible',
            field=models.BooleanField(default=True, help_text='Если выключено, раздел скрыт от студентов', verbose_name='Видим студентам'),
        ),
    ]
