# Generated by Django 4.2.18 on 2026-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursesection_add_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='visible',
            field=models.BooleanField(default=True, help_text='Если выключено, тема скрыта от студентов', verbose_name='Видима студентам'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='visible',
            field=models.BooleanField(default=True, help_text='Если выключено, единица скрыта от студентов', verbose_name='Видима студентам'),
        ),
    ]
