# Generated by Django 4.2.18 on 2026-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_topic_unit_add_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='grading_type',
            field=models.CharField(blank=True, choices=[('pass_fail', 'Зачтено / не зачтено'), ('score_100', 'Баллы (0–100)')], help_text='Только для контрольных единиц. Укажите способ оценивания.', max_length=20, null=True, verbose_name='Тип оценки'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='content_type',
            field=models.CharField(choices=[('methodical', 'Методическая единица'), ('lecture', 'Лекционная единица'), ('control', 'Контрольная единица')], default='file', max_length=30, verbose_name='Тип содержимого'),
        ),
    ]
