# Generated by Django 4.2.18 on 2026-07-16 13:30

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentgroup_education_form'),
        ('course', '0011_learningunit_content_types_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, help_text='Загруженный студентом файл', null=True, upload_to=course.models.student_answer_upload_to, verbose_name='Файл ответа')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('checked', models.BooleanField(default=False, help_text='Преподаватель проверил работу', verbose_name='Проверена')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Оценка (например, 0–100)', null=True, verbose_name='Балл')),
                ('passed', models.BooleanField(blank=True, help_text='Зачтено / не зачтено', null=True, verbose_name='Зачтено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения ответа')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('checked_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения проверки')),
                ('learning_unit', models.ForeignKey(limit_choices_to={'content_type': 'control'}, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course.learningunit', verbose_name='Контрольная единица')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'unique_together': {('student', 'learning_unit')},
            },
        ),
    ]
