# Generated by Django 4.2.18 on 2026-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_student_answer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=10, help_text='Максимальный балл за эту контрольную единицу (по умолчанию 10).', verbose_name='Максимальный балл'),
        ),
    ]
