# Generated by Django 4.2.18 on 2026-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_add_max_score_to_learningunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='comment',
            field=models.TextField(blank=True, help_text='Текстовый комментарий к оценке', null=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='grading_type',
            field=models.CharField(blank=True, choices=[('pass_fail', 'Зачтено / не зачтено'), ('score_100', 'Баллы')], help_text='Только для контрольных единиц. Укажите способ оценивания.', max_length=20, null=True, verbose_name='Тип оценки'),
        ),
    ]
