# Generated by Django 4.2.18 on 2026-07-17 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_add_comment_to_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст объявления')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается на главных страницах', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата сокрытия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='course.course', verbose_name='Курс')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Скрыто пользователем')),
            ],
            options={
                'verbose_name': 'Объявление курса',
                'verbose_name_plural': 'Объявления курсов',
                'ordering': ['-created_at'],
            },
        ),
    ]
