# Generated by Django 4.2.18 on 2026-07-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentgroup_education_form'),
        ('course', '0015_add_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementDismiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата скрытия')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='course.courseannouncement', verbose_name='Объявление')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Скрытие объявления студентом',
                'verbose_name_plural': 'Скрытия объявлений студентами',
                'unique_together': {('announcement', 'student')},
            },
        ),
    ]
