# Generated by Django 4.2.18 on 2026-07-17 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentgroup_education_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_add_dismiss_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementdismiss',
            options={'verbose_name': 'Скрытие объявления', 'verbose_name_plural': 'Скрытия объявлений'},
        ),
        migrations.AlterUniqueTogether(
            name='announcementdismiss',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courseannouncement',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='courseannouncement',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='courseannouncement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='announcementdismiss',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='announcementdismiss',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to='students.student', verbose_name='Студент'),
        ),
        migrations.AddConstraint(
            model_name='announcementdismiss',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('announcement', 'user'), name='unique_dismiss_user'),
        ),
        migrations.AddConstraint(
            model_name='announcementdismiss',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('announcement', 'student'), name='unique_dismiss_student'),
        ),
    ]
