# Generated by Django 4.2.18 on 2026-07-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_question_choice'),
        ('course', '0017_alter_dismiss_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='test',
            field=models.ForeignKey(blank=True, help_text='Прикрепить тест для прохождения студентом (только для контрольных единиц).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_units', to='testing.test', verbose_name='Тест'),
        ),
    ]
