# Generated by Django 4.2.18 on 2026-07-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_subgroup_number'),
        ('course', '0018_learningunit_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название шага')),
                ('content', models.TextField(blank=True, help_text='Текст/материал, излагаемый на данном шаге', null=True, verbose_name='Материал шага')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='content_type',
            field=models.CharField(choices=[('methodical', 'Методическая единица'), ('lecture', 'Лекционная единица'), ('control', 'Контрольная единица'), ('step_by_step', 'Пошаговая единица')], default='file', max_length=30, verbose_name='Тип содержимого'),
        ),
        migrations.CreateModel(
            name='StepQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.step', verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Вопрос шага',
                'verbose_name_plural': 'Вопросы шагов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='course.stepquestion', verbose_name='Вопрос шага')),
            ],
            options={
                'verbose_name': 'Вариант ответа шага',
                'verbose_name_plural': 'Варианты ответов шагов',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='step',
            name='learning_unit',
            field=models.ForeignKey(limit_choices_to={'content_type': 'step_by_step'}, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='course.learningunit', verbose_name='Пошаговая единица'),
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='course.step', verbose_name='Шаг')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
                'unique_together': {('student', 'step')},
            },
        ),
    ]
