# Generated by Django 4.2.18 on 2026-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_step_by_step_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Если включено, курс помечен как удалённый и не отображается в списках.', verbose_name='Удалён (софт)'),
        ),
    ]
