# Generated by Django 4.2.18 on 2026-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Если включено, единица помечена как удалённая.', verbose_name='Удалена (софт)'),
        ),
    ]
