# Generated by Django 4.2.18 on 2026-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_unit_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepprogress',
            name='answers',
            field=models.JSONField(blank=True, help_text='Выбранные варианты ответов: {question_id: [choice_id, ...]}', null=True, verbose_name='Ответы студента'),
        ),
    ]
