# Generated by Django 4.2.18 on 2026-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_question_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.PositiveIntegerField(verbose_name='ID оригинального теста')),
                ('author_id', models.PositiveIntegerField(verbose_name='ID автора')),
                ('author_name', models.CharField(max_length=300, verbose_name='Автор')),
                ('subject_id', models.PositiveIntegerField(verbose_name='ID дисциплины')),
                ('subject_name', models.CharField(max_length=500, verbose_name='Дисциплина')),
                ('name', models.CharField(max_length=300, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('export_data', models.TextField(verbose_name='JSON-данные теста')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания теста')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Удалённый тест',
                'verbose_name_plural': 'Удалённые тесты',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
