# Generated by Django 4.2.18 on 2026-07-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_step_by_step_models'),
        ('chat', '0002_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='students.studentgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Групповой чат',
                'verbose_name_plural': 'Групповые чаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, help_text='Помечается после того, как все студенты группы прочитали (для простоты — не используется активно).', verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupchat', verbose_name='Комната')),
                ('sender_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_messages', to='students.student', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение группового чата',
                'verbose_name_plural': 'Сообщения групповых чатов',
                'ordering': ['created_at'],
            },
        ),
    ]
