# Generated by Django 4.2.18 on 2026-07-21 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название группы')),
                ('users', models.ManyToManyField(blank=True, related_name='teacher_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Группа преподавателей',
                'verbose_name_plural': 'Группы преподавателей',
            },
        ),
    ]
