# Generated by Django 4.2.18 on 2026-07-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachergroup',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название группы'),
        ),
    ]
