# Generated by Django 4.2.18 on 2026-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Пример: 6-05-0612-01, 1-40-01-01', max_length=20, verbose_name='Шифр')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название шифра')),
            ],
            options={
                'verbose_name': 'Шифр',
                'verbose_name_plural': 'Шифры',
            },
        ),
    ]
