# Generated by Django 4.2.18 on 2026-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifr',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Квалификация'),
        ),
    ]
