# Generated by Django 4.2.18 on 2026-07-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_create_roles'),
        ('umo', '0002_shifr_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifr',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Факультет, к которому относится данный шифр', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifrs', to='structure.faculty', verbose_name='Факультет'),
        ),
    ]
