# Generated by Django 4.2.18 on 2026-07-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_faculty_group_numbers'),
        ('umo', '0003_shifr_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifr',
            options={'verbose_name': 'Код специальности', 'verbose_name_plural': 'Коды специальностей'},
        ),
        migrations.AlterField(
            model_name='shifr',
            name='code',
            field=models.CharField(help_text='Пример: 6-05-0612-01, 1-40-01-01', max_length=20, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='shifr',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Факультет, к которому относится данный код специальности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifrs', to='structure.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='shifr',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название'),
        ),
    ]
