# Generated by Django 4.2.18 on 2026-07-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое наименование')),
                ('identifier', models.CharField(help_text='Для внутренних нужд, не отображается в интерфейсе', max_length=50, unique=True, verbose_name='Идентификатор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='structure.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
