# Generated by Django 4.2.18

from django.db import migrations


def create_initial_structure(apps, schema_editor):
    University = apps.get_model('structure', 'University')
    Faculty = apps.get_model('structure', 'Faculty')

    university = University.objects.create(
        full_name='Московский государственный университет имени М.В. Ломоносова',
        short_name='МГУ',
        identifier='msu',
    )

    faculties = [
        ('fmechmat', 'Механико-математический факультет', 'Мехмат'),
        ('fvmk', 'Факультет вычислительной математики и кибернетики', 'ВМК'),
        ('fphys', 'Физический факультет', 'Физфак'),
        ('fchem', 'Химический факультет', 'Химфак'),
        ('fbio', 'Биологический факультет', 'Биофак'),
        ('fgeo', 'Геологический факультет', 'Геофак'),
        ('ffil', 'Филологический факультет', 'Филфак'),
    ]

    for ident, full, short in faculties:
        Faculty.objects.create(
            university=university,
            full_name=full,
            short_name=short,
            identifier=ident,
        )


def remove_initial_structure(apps, schema_editor):
    University = apps.get_model('structure', 'University')
    University.objects.filter(identifier='msu').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_structure, remove_initial_structure),
    ]