# Generated by Django 4.2.18 on 2026-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='identifier',
            field=models.CharField(blank=True, help_text='Для внутренних нужд, не отображается в интерфейсе', max_length=50, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='identifier',
            field=models.CharField(blank=True, help_text='Для внутренних нужд, не отображается в интерфейсе', max_length=50, null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='university',
            name='identifier',
            field=models.CharField(blank=True, help_text='Для внутренних нужд, не отображается в интерфейсе', max_length=50, null=True, unique=True, verbose_name='Идентификатор'),
        ),
    ]
