# Generated by Django 4.2.18 on 2026-07-15 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0003_alter_department_identifier_alter_faculty_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_head', to=settings.AUTH_USER_MODEL, verbose_name='Заведующий кафедрой'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties_as_dean', to=settings.AUTH_USER_MODEL, verbose_name='Декан'),
        ),
    ]
