# Generated by Django 4.2.18 on 2026-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_create_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='group_numbers',
            field=models.CharField(blank=True, help_text='Через запятую: первые цифры номеров групп этого факультета, например: 1,2,3', max_length=200, null=True, verbose_name='Номера групп'),
        ),
    ]
