from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('create/', views.course_create, name='course_create'),
    path('<int:course_id>/delete/', views.course_delete, name='course_delete'),
    path('<int:course_id>/hard-delete/', views.course_hard_delete, name='course_hard_delete'),
    path('archive/', views.course_archive, name='course_archive'),
    path('<int:course_id>/restore/', views.course_restore, name='course_restore'),
    path('<int:course_id>/edit/', views.course_edit, name='course_edit'),
    path('section/<int:section_id>/delete/', views.section_delete, name='section_delete'),
    path('section/<int:section_id>/toggle-visibility/', views.section_toggle_visibility, name='section_toggle_visibility'),
    path('topic/<int:topic_id>/delete/', views.topic_delete, name='topic_delete'),
    path('unit/<int:unit_id>/delete/', views.unit_delete, name='unit_delete'),
    path('section/<int:section_id>/add-topic/', views.topic_add, name='topic_add'),
    path('topic/<int:topic_id>/add-unit/', views.unit_add_to_topic, name='unit_add_to_topic'),
    path('section/<int:section_id>/add-unit/', views.unit_add_to_section, name='unit_add_to_section'),
    path('unit/<int:unit_id>/edit/', views.unit_edit, name='unit_edit'),
    path('topic/<int:topic_id>/edit/', views.topic_edit, name='topic_edit'),
    path('section/<int:section_id>/edit/', views.section_edit, name='section_edit'),
    path('topic/<int:topic_id>/toggle-visibility/', views.topic_toggle_visibility, name='topic_toggle_visibility'),
    path('unit/<int:unit_id>/toggle-visibility/', views.unit_toggle_visibility, name='unit_toggle_visibility'),
    path('unit/<int:unit_id>/answer/', views.student_answer, name='student_answer'),
    path('unit/<int:unit_id>/take-test/', views.start_test, name='start_test'),
    path('<int:course_id>/view/', views.course_view, name='course_view'),
    path('<int:course_id>/enroll-groups/', views.course_enroll_groups, name='course_enroll_groups'),
    path('groupstudent/<int:gs_id>/unenroll/', views.course_unenroll_group, name='course_unenroll_group'),
    path('<int:course_id>/grades/', views.course_grades, name='course_grades'),
    path('<int:course_id>/student-grades/', views.student_grades, name='student_grades'),
    path('answer/<int:answer_id>/check/', views.check_answer, name='check_answer'),
    path('<int:course_id>/announcement/create/', views.announcement_create, name='announcement_create'),
    path('announcement/<int:announcement_id>/hide/', views.announcement_hide, name='announcement_hide'),
    path('announcement/<int:announcement_id>/dismiss/', views.announcement_dismiss, name='announcement_dismiss'),
    path('announcement/<int:announcement_id>/restore/', views.announcement_restore, name='announcement_restore'),
    path('<int:course_id>/student/<int:student_id>/unit/<int:unit_id>/check-no-submission/', views.check_answer_no_submission, name='check_answer_no_submission'),

    # Пошаговые единицы
    path('step-by-step/', views.step_by_step_list, name='step_by_step_list'),
    path('step-by-step/create/', views.step_by_step_create, name='step_by_step_create'),
    path('step-by-step/<int:unit_id>/wizard/', views.step_by_step_wizard, name='step_by_step_wizard'),
    path('step-by-step/<int:unit_id>/delete/', views.step_by_step_soft_delete, name='step_by_step_soft_delete'),
    path('step-by-step/archive/', views.step_by_step_archive, name='step_by_step_archive'),
    path('step-by-step/<int:unit_id>/restore/', views.step_by_step_restore, name='step_by_step_restore'),
    path('step-by-step/<int:unit_id>/hard-delete/', views.step_by_step_hard_delete, name='step_by_step_hard_delete'),
    path('step-by-step/<int:unit_id>/edit/', views.step_by_step_edit, name='step_by_step_edit'),
    path('step-by-step/<int:unit_id>/step/add/', views.step_add, name='step_add'),
    path('step/<int:step_id>/edit/', views.step_edit, name='step_edit'),
    path('step/<int:step_id>/delete/', views.step_delete, name='step_delete'),
    path('step/<int:step_id>/question/add/', views.step_question_add, name='step_question_add'),
    path('question/<int:question_id>/edit/', views.step_question_edit, name='step_question_edit'),
    path('question/<int:question_id>/delete/', views.step_question_delete, name='step_question_delete'),
    path('step-by-step/<int:unit_id>/take/', views.step_by_step_take, name='step_by_step_take'),
    path('step-by-step/<int:unit_id>/preview/', views.step_by_step_preview, name='step_by_step_preview'),

    # Права преподавателей
    path('<int:course_id>/teacher-permission/add/', views.teacher_permission_add, name='teacher_permission_add'),
    path('<int:course_id>/teacher-permission/<int:up_id>/remove/', views.teacher_permission_remove, name='teacher_permission_remove'),
    path('<int:course_id>/group-permission/add/', views.group_permission_add, name='group_permission_add'),
    path('<int:course_id>/group-permission/<int:gp_id>/remove/', views.group_permission_remove, name='group_permission_remove'),
]
